server:
  port: 8080
  session:
    timeout: 10
  tomcat:
    uri-encoding: UTF-8
spring:
  mvc:
    static-path-pattern: /**

kubernetes:
  config:
    config-path: /root/.kube/config
    master: 10.68.7.127:6443
    token: D:/k8s/127/token